services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
      secrets:
        - "HF_TOKEN"
    container_name: fastapi-dev
    environment:
      - SPEECH_SPEED=${SPEECH_SPEED-1.0}
    restart: always
    volumes:
      - .:/app
    ports:
      - '8000:8000'
secrets:
  HF_TOKEN:
    environment: "HF_TOKEN"