services:
  server:
    build:
      context: .
    restart: unless-stopped
    ports:
      - '8000:8000'
    environment:
      - SPEECH_SPEED=${SPEECH_SPEED:-0.9}  # Default to 0.9 if SPEECH_SPEED is not set
      - USE_CUDA=${USE_CUDA:-0}            # Default to 0 if USE_CUDA is not set