FROM python:3.10.12-slim

WORKDIR /app

COPY ./requirements.txt /app
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install pytest httpx pydub pytest-repeat --no-cache-dir

ENTRYPOINT pytest
