version: '3.9'
services:
  server:
    build:
      context: .
    environment:
      - SPEECH_SPEED=${SPEECH_SPEED}
      - MP_WORKERS=${MP_WORKERS}
      - USE_MP=${USE_MP}
    restart: unless-stopped
    ports:
      - '8080:8000'
    shm_size: ${SHM_SIZE}
