version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fastapi-dev
    environment:
      - SPEECH_SPEED=${SPEECH_SPEED-1.0}
    restart: always
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    shm_size: ${SHM_SIZE-2gb}
