version: '3.9'
services:
  server:
    build:
      context: .
    environment:
      - SPEECH_SPEED=${SPEECH_SPEED}
      - USE_CUDA=True
    restart: unless-stopped
    ports:
      - '8000:8000'
    shm_size: ${SHM_SIZE}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]